TripPlannerSolution/TripPlanner.WebApplication/Controllers/TouristAttractionsController.cs
namespace TripPlanner.WebApplication.Controllers
{
    using System.Collections.Generic;
    using System.Web.Configuration;
    using System.Web.Mvc;
    using RestSharp;
    using TripPlanner.WebApplication.ViewModels;

    [RoutePrefix("touristattractions")]
    public class TouristAttractionsController : Controller
    {
        [Route]
        public ViewResult GetAllTouristAttractions()
        {
            var client = new RestClient(WebConfigurationManager.AppSettings["webApiUrl"]);
            var request = new RestRequest("api/touristattractions/", Method.GET);
            var queryResult = client.Execute<List<TouristAttractionForListing>>(request).Data;

            return this.View(queryResult);
        }

        [Route("{id}")]
        public ViewResult GetSingleAttraction(int id)
        {
            var client = new RestClient(WebConfigurationManager.AppSettings["webApiUrl"]);
            var request = new RestRequest("api/touristattractions/" + id, Method.GET);
            var queryResult = client.Execute<TouristAttractionDetailed>(request).Data;

            return this.View(queryResult);
        }

        [Route("suggest")]
        public ViewResult SuggestAttraction()
        {
            return this.View();
        }

        [HttpPost]
        [Route("suggest")]
        public ViewResult SuggestAttraction(TouristAttractionSuggestion suggestion)
        {
            if (this.ModelState.IsValid)
            {
                var client = new RestClient(WebConfigurationManager.AppSettings["webApiUrl"]);
                var request = new RestRequest("api/suggestedattractions/add", Method.POST)
                {
                    RequestFormat = DataFormat.Json
                };
                request.AddBody(suggestion);
                client.Execute(request);

                return this.View("thanks");
            }
            else
            {
                return this.View();
            }
        }

        [Route("thanks")]
        public ViewResult Thanks()
        {
            return this.View();
        }
    }
}

TripPlannerSolution/TripPlanner.WebApplication/Views/TouristAttractions/GetAllTouristAttractions.cshtml
@using System.Web.Mvc.Html
@model IEnumerable<TripPlanner.WebApplication.ViewModels.TouristAttractionForListing>

@{
    ViewBag.Title = "Tourist Attractions";
}

<div>@Html.ActionLink("Suggest new!", "Suggest", "TouristAttractions")</div>

<h2>Tourist attractions:</h2>

@foreach (var a in Model)
{
    <div class="item">
        <h3>@Html.ActionLink(@a.Name, @a.ID.ToString(), "TouristAttractions")</h3>
    </div>
}

TripPlannerSolution/TripPlanner.WebApplication/Views/TouristAttractions/GetSingleAttraction.cshtml
@using TripPlanner.WebApplication.ViewModels
@model TouristAttractionDetailed

@{
    ViewBag.Title = "GetSingleAttraction";
    ViewBag.Key = "AIzaSyC4Cd2mMCpJTMdONRDJ4U3UUVblVq7pdhw";
    ViewBag.MapSource = "https://www.google.com/maps/embed/v1/place?key=" + ViewBag.Key + "&q=" 
        + @Model.Coordinates.ToDecimalDegreesFormatString();
}

<div>@Html.ActionLink("Go back to attraction list", string.Empty, "TouristAttractions")</div>

<div>
    <h1>@Model.Name</h1>
    @if (Model.Category.Name != null)
    {
        <div>(@Model.Category.Name)</div>
    }
</div>

<hr/>

@if (Model.Address != null)
{
    <div>
        <h3>
            <p>@Model.Address.Street @Model.Address.Number</p>
            <p>@Model.Address.PostCode, @Model.Address.City</p>
            <p>@Model.Address.Country</p>
        </h3>
    </div>
}

<hr />

<div>
    <h3>Additional information:</h3>
    <p>Adults only:
        @if (Model.AdultsOnly)
        {
            <img src="http://img2.wikia.nocookie.net/__cb20080127132158/finalfantasy/images/6/69/Yes_check.png" height=10 width=10/>
        }
        else
        {
            <img src="http://cliparts.co/cliparts/kTM/dBd/kTMdBd9Tj.png" height=10 width=10/>
        }
    </p>
    <p>
        Disabled access:
        @if (Model.DisabledAccess)
        {
            <img src="http://img2.wikia.nocookie.net/__cb20080127132158/finalfantasy/images/6/69/Yes_check.png" height=10 width=10/>
        }
        else
        {
            <img src="http://cliparts.co/cliparts/kTM/dBd/kTMdBd9Tj.png" height=10 width=10/>
        }
    </p>
</div>

<hr />

@if (Model.OpeningHours.IsAssignedWithAnyDayValue())
{
    <h3>Opening hours:</h3>
    <ul>
        @if (Model.OpeningHours.Monday != null)
        {
            <li>Monday: @Model.OpeningHours.Monday.ToViewModelFormatString()</li>
        }
        @if (Model.OpeningHours.Tuesday != null)
        {
            <li>Tuesday: @Model.OpeningHours.Tuesday.ToViewModelFormatString()</li>
        }
        @if (Model.OpeningHours.Wednesday != null)
        {
            <li>Wednesday: @Model.OpeningHours.Wednesday.ToViewModelFormatString()</li>
        }
        @if (Model.OpeningHours.Thursday != null)
        {
            <li>Thursday: @Model.OpeningHours.Thursday.ToViewModelFormatString()</li>
        }
        @if (Model.OpeningHours.Friday != null)
        {
            <li>Friday: @Model.OpeningHours.Friday.ToViewModelFormatString()</li>
        }
        @if (Model.OpeningHours.Saturday != null)
        {
            <li>Saturday: @Model.OpeningHours.Saturday.ToViewModelFormatString()</li>
        }
        @if (Model.OpeningHours.Sunday != null)
        {
            <li>Sunday: @Model.OpeningHours.Sunday.ToViewModelFormatString()</li>
        }
    </ul>

    <hr />
}

@if (Model.Price.BasePrice != null)
{
<h3>Prices:</h3>
    <ul>
        <li>Base price: @Model.Price.BasePrice.Value.ToString("c")</li>
        @if (Model.Price.Discounts != null)
        {
            <li>Discounts:</li>
            <ol>
                @foreach (var d in Model.Price.Discounts)
                {
                    <li>@d.Description, @d.Price.ToString("c")</li>
                }
            </ol>
        }
    </ul>

    <hr />
}

<h3>On map:</h3>
<iframe
    width="450"
    height="450"
    style="border: 3; border-color: #FFFFFF"
    src=@ViewBag.MapSource>
</iframe>

TripPlannerSolution/TripPlanner.WebApplication/Views/TouristAttractions/SuggestAttraction.cshtml
@model TripPlanner.WebApplication.ViewModels.TouristAttractionSuggestion

<script type="text/javascript"
        src="http://maps.google.com/maps/api/js?sensor=false">
</script>
<script type="text/javascript">

    $(document).ready(function () {
        initMap();
    });

    var marker;

    function initMap() {
        var myLatlng = { lat: 51.109614, lng: 17.031472 };

        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 16,
            center: myLatlng
        });

        var marker = new google.maps.Marker({
            map: map,
            draggable: true
        });

        map.addListener('click', function (event) {
            changeMarkerPosition(marker, event.latLng);
        });

        google.maps.event.addListener(map, "click", function (event) {
            document.getElementById("Coordinates_Latitude").value = marker.getPosition().lat();
            document.getElementById("Coordinates_Longitude").value = marker.getPosition().lng();
        });

        google.maps.event.addListener(marker, 'dragend', function (event) {
            document.getElementById("Coordinates_Latitude").value = this.getPosition().lat();
            document.getElementById("Coordinates_Longitude").value = this.getPosition().lng();
        });
    }

    function changeMarkerPosition(marker, location) {
        marker.setPosition(location);
    }

</script>  

@{
    ViewBag.Title = "SuggestAttraction";
}

<div>@Html.ActionLink("Go back to attraction list", string.Empty, "TouristAttractions")</div>

<h2>SuggestAttraction</h2>
<h4>Did we miss something?</h4>
<hr/>

<div id="map" style="width: 640px; height: 480px;"></div>

<hr/>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr/>

        <div class="form-group">
            @Html.LabelFor(model => model.Coordinates.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="Coordinates_Latitude" name="Coordinates.Latitude" type="text" value="" readOnly>
                @Html.ValidationMessageFor(model => model.Coordinates.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coordinates.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="Coordinates_Longitude" name="Coordinates.Longitude" type="text" value="" readOnly>
                @Html.ValidationMessageFor(model => model.Coordinates.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr/>

        <div class="form-group">
            @Html.LabelFor(model => model.Address.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address.PostCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.DisabledAccess, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DisabledAccess)
                    @Html.ValidationMessageFor(model => model.DisabledAccess, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdultsOnly, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AdultsOnly)
                    @Html.ValidationMessageFor(model => model.AdultsOnly, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <hr/>

        <div class="form-group">
            @Html.LabelFor(model => model.Price.BasePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Price.BasePrice)
                    @Html.ValidationMessageFor(model => model.Price.BasePrice, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <hr />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Suggest" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Go back to attraction list", string.Empty)
</div>

TripPlannerSolution/TripPlanner.WebApplication/Views/TouristAttractions/Thanks.cshtml
@{
    ViewBag.Title = "Thanks";
}

<h2>Thanks</h2>
<div>Thanks for suggestion</div>
<h3>@Html.ActionLink("Back to list", string.Empty, "TouristAttractions")</h3>